#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import shutil
from pip._internal import main
import os
from pathlib import Path

def remove_bin(dir_path):
	shutil.rmtree(dir_path)
	main(["uninstall",'--yes','neovim'])


@remove_path

if __name__ == "__main__":
	@dir_path
	@app_path
	remove_bin(dir_path)
	remove_path(app_path)
